base/base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("goals_tracker.urls"))
]

base/goals_tracker/urls.py
from django.urls import path
from . import views

app_name = "goals_tracker"

urlpatterns = [
  # authentication
  path("login", views.login_view, name="login"),
  path("logout", views.logout_view, name="logout"),
  path("register", views.register, name="register"),  

  # home
  path("", views.index, name="index"),
  path("daily-systems", views.daily_systems, name="daily_systems"),
  path("big-goals", views.big_goals, name="big_goals"),
  path("create-big-goal", views.big_goals, name="create_big_goal"),
  path("delete-old-goal", views.big_goals, name='delete_old_goal'),
  path("get-user-data", views.get_user_data, name="get_user_data"),

  # big goal page
  path("big-goal/<str:title>", views.big_goal, name="big_goal"),
  path("big-goal/<str:title>/create-daily-system", views.daily_system, name="create_daily_system"),
  path("big-goal/<str:title>/delete-daily-system", views.daily_system, name="delete_daily_system"),

  # complete a daily action
  path("all-completed-daily-systems", views.all_completed_daily_systems, name="all_completed_daily_systems"),
  path("mark-complete-daily-system", views.mark_complete_daily_system, name="mark_complete_daily_system"),
  path("mark-incomplete-daily-system", views.mark_incomplete_daily_system, name="mark_incomplete_daily_system"),
]

base/goals_tracker/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import date

class User(AbstractUser):
  def __str__(self):
    return self.username

class BaseModel(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(blank=True)

    class Meta:
        abstract = True

class BigGoal(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start = models.DateField(default=date.today)
    deadline = models.DateField()

    def __str__(self):
        return self.title
    
    def serialize(self):
        return {
            "id": self.id,
            "title": self.title,
            "user": self.user.username,
            "description": self.description,
            "start": self.start.strftime("%Y-%m-%d"),
            "deadline": self.deadline.strftime("%Y-%m-%d"),
        }

class DailySystem(models.Model):
    big_goal = models.ForeignKey(BigGoal, on_delete=models.CASCADE)
    action = models.CharField(max_length=300)

    def __str__(self):
        return self.action

    def serialize(self):
        return {
            "id": self.id,
            "big_goal": self.big_goal.title,
            "action": self.action,
        }

class DailySystemCheckIn(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    big_goal = models.ForeignKey(BigGoal, on_delete=models.CASCADE, default="")
    daily_system = models.ForeignKey(DailySystem, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return f"{self.user.username}'s check-in for {self.daily_system.action} on {self.date}"
    
    def serialize(self):
        return {
            "user": self.user.username,
            "big_goal": self.big_goal.title,
            "daily_system": self.daily_system.action,
            "date": self.date,
        }
    

base/goals_tracker/views.py
import json

from collections import defaultdict
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.db import IntegrityError
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta, datetime, date
import json

from .models import User, BigGoal, DailySystem, DailySystemCheckIn

# GLOBAL FUNCTION
def all_completed_daily_systems(request):
   completed_daily_systems = DailySystemCheckIn.objects.filter(user=request.user)

   completed_daily_systems_data = defaultdict(lambda: defaultdict(list))

   for completed in completed_daily_systems:
      data = completed.serialize()
      date = data.get('date').strftime('%a-%b-%d-%Y')  # Get date first
      big_goal = data.get('big_goal')
      daily_system = data.get('daily_system')

      if daily_system not in completed_daily_systems_data[date][big_goal]:
         completed_daily_systems_data[date][big_goal].append(daily_system)

   completed_daily_systems_data = {date: dict(goals) for date, goals in completed_daily_systems_data.items()}

   return JsonResponse(completed_daily_systems_data, safe=False) 

def mark_incomplete_daily_system(request):
   try:
      data = json.loads(request.body)
      big_goal_title = data.get("bigGoal")
      daily_system_action = data.get("dailySystem")
      date_str = data.get("date")

      if not all([big_goal_title, daily_system_action, date_str]):
          return JsonResponse({"message": "Missing required fields"}, status=400) 
      
      print(big_goal_title, daily_system_action, date_str)
      
      parsed_date = datetime.strptime(date_str, "%a-%b-%d-%Y").date()
      big_goal_obj = get_object_or_404(BigGoal, user=request.user, title=big_goal_title)
      daily_system_obj = get_object_or_404(DailySystem, big_goal=big_goal_obj, action=daily_system_action)
      daily_system_checkins = DailySystemCheckIn.objects.filter(user=request.user, big_goal=big_goal_obj, daily_system=daily_system_obj, date=parsed_date)

      for checkin in daily_system_checkins:
         checkin.delete()

      return JsonResponse({"message": f"All {daily_system_action} entries for {parsed_date} deleted"}, status=201)
   
   except ValueError:
      return JsonResponse({"message": "Invalid date format"}, status=400)
   except Exception as e:
      return JsonResponse({'message': f'An error occurred: {str(e)}'}, status=500)

def mark_complete_daily_system(request):
   try:
      data = json.loads(request.body)
      big_goal_title = data.get("bigGoal")
      daily_system_action = data.get("dailySystem")
      date_str = data.get("date")

      if not all([big_goal_title, daily_system_action, date_str]):
         return JsonResponse({"message": "Missing required fields"}, status=400)
      
      parsed_date = datetime.strptime(date_str, "%a-%b-%d-%Y").date()
      big_goal_obj = get_object_or_404(BigGoal, user=request.user, title=big_goal_title)
      daily_system_obj = get_object_or_404(DailySystem, big_goal=big_goal_obj, action=daily_system_action)

      # Check if DailySystemCheckIn already exists for the given date
      existing_checkin = DailySystemCheckIn.objects.filter(user=request.user,
                                                              big_goal=big_goal_obj,
                                                              daily_system=daily_system_obj,
                                                              date=parsed_date).exists()
      if existing_checkin:
         return JsonResponse({"message": f"{daily_system_action} already completed at {parsed_date}"}, status=400)

      # Create and save DailySystemCheckIn
      daily_system_checkin = DailySystemCheckIn(
         user=request.user,
         big_goal=big_goal_obj,
         daily_system=daily_system_obj,
         date=parsed_date,
      )
      daily_system_checkin.save()

      return JsonResponse({"message": f"{daily_system_action} completed at {parsed_date}"}, status=201)
   except ValueError:
      return JsonResponse({"message": "Invalid date format"}, status=400)
   except Exception as e:
      return JsonResponse({'message': f'An error occurred: {str(e)}'}, status=500)

def big_goal_data(request, title):
   original_title = title.replace('-', ' ')

   # Big Goal
   big_goal = get_object_or_404(BigGoal, user=request.user, title=original_title)
   big_goal_data = big_goal.serialize()

   # Completed Daily Systems
   completed_daily_systems_content = all_completed_daily_systems(request).content.decode('utf-8')
   completed_daily_systems_data = json.loads(completed_daily_systems_content)
 
   # Retrieve related Daily Systems
   daily_systems = DailySystem.objects.filter(big_goal=big_goal)
   daily_systems_data = []
   daily_systems_actions = ''
   for system in daily_systems:
      data = system.serialize()
      daily_systems_actions += data["action"] + ","
      daily_systems_data.append(data)

   # Create timeline
   start_date = datetime.strptime(big_goal_data["start"], "%Y-%m-%d")
   end_date = datetime.strptime(big_goal_data["deadline"], "%Y-%m-%d")
   all_dates = []

   for i in range((end_date - start_date).days + 1):
      current_date = (start_date + timedelta(days=i)).strftime('%a-%b-%d-%Y')
      current_date_data = {
         "current": current_date,
         "actions": [],
      }

      if current_date in completed_daily_systems_data:
         completed_on_date = completed_daily_systems_data[current_date]

         for daily in daily_systems_data:
            goal = daily["big_goal"]
            action = daily["action"]
            if goal in completed_on_date and action in completed_on_date.get(goal):
               current_date_data["actions"].append(action)
        
      all_dates.append(current_date_data)

   timeline = {
      "start": start_date.strftime('%B %d, %Y'),
      "deadline": end_date.strftime('%B %d, %Y'),
      "all_dates": all_dates,
   }

   # Calculate percentage completion
   total_days = (end_date - start_date).days
   days_elapsed = (date.today() - start_date.date()).days
   percentage_completion = round(max(0, min((days_elapsed / total_days) * 100, 100)), 1)

   return {
      "title_unedited": title,
      "big_goal": big_goal_data,
      "timeline": timeline,
      "daily_systems": daily_systems_data,
      "actions": daily_systems_actions,
      "percentage_completion": percentage_completion,
   }


# BIG GOAL PAGE
def daily_system(request, title):
   # delete daily system
   if request.method == "DELETE":
      data = json.loads(request.body)

      id = int(data.get("id", 0))
      big_goal = data.get("big_goal", "")
      action = data.get("action", "")

      print(data)

      try: 
         big_goal_instance = get_object_or_404(BigGoal, user=request.user, title=big_goal)
         daily_system = get_object_or_404(DailySystem, id=id, big_goal=big_goal_instance, action=action)
         daily_system.delete()
         return JsonResponse({'message': 'Daily System deleted successfully'})
      except Http404:
         return JsonResponse({'message': 'Daily System not found'}, status=404)
      except Exception as e:
         return JsonResponse({'message': f'An error occurred: {str(e)}'}, status=500)


   # create daily system
   if request.method == "POST":
      data = json.loads(request.body)
      print(data)
      print(title)

      # get contents from Daily System Form submission
      big_goal = data.get("bigGoal", "")
      action = data.get("action", "")

      big_goal = get_object_or_404(BigGoal, user=request.user, title=big_goal)

      # insert contents to the DailySystem Model
      daily_system = DailySystem(
         big_goal = big_goal,
         action = action,
      ) 
      daily_system.save()

      return JsonResponse({"message": "Daily System created successfully."}, status=201)

def big_goal(request, title):
   if request.method == "GET":
      big_goal_page = big_goal_data(request, title)

      return render(request, "goals_tracker/big_goal_page.html", big_goal_page)


# HOME
def get_user_data(request):
   if request.method == "GET":
      return JsonResponse(user_data(request), status=201) 

def user_data(request):
   user = request.user
   user_obj = get_object_or_404(User, username=user.username)

   # Serialize only necessary user data
   return {
        'id': user_obj.id,
        'username': user_obj.username,
        'first_name': user_obj.first_name,
        'last_name': user_obj.last_name,
        'email': user_obj.email,
    }

def daily_systems(request):
   # get all daily systems
   if request.method == "GET":
        user = request.user

        container = []
        # Retrieve all Big Goals of the user
        big_goals_queryset = BigGoal.objects.filter(user=user).order_by("-start")
        for big_goal in big_goals_queryset:
           deadline = big_goal.deadline
           if deadline > date.today():
            # Retrieve all Daily Systems of the user
            big_goal_actions = DailySystem.objects.filter(big_goal=big_goal)

            for action in big_goal_actions:
               container.append(action)

        completed_daily_systems_content = all_completed_daily_systems(request).content.decode('utf-8')
        completed_daily_systems_data = json.loads(completed_daily_systems_content)
        today = date.today().strftime('%a-%b-%d-%Y')
        completed_today = completed_daily_systems_data.get(today, {})

        print(completed_today)

        # Serialize queryset into JSON format
        daily_systems = []
        for action in container:
           data = action.serialize()
           big_goal = data["big_goal"]
           action = data["action"]

           print(completed_today.get(big_goal))

           big_goal_in_completed_today = completed_today.get(big_goal, {})

base/goals_tracker/templates/goals_tracker/big_goal_page.html
{% extends "goals_tracker/layout.html" %}

{% block title %}
{{ big_goal.title }} - Goal Tracker
{%endblock %}

{% block body %}

<main class="big-goal-page" id="big-goal-page">
  {% comment %} Timeline / Daily Actions {% endcomment %}
  <div class="big-goal-content"> 
    {% comment %} Details {% endcomment %}
    <section class="goal-details-section big-goal">
      <div class="big-goal-content--headers">
        <h1 class="m-0 align-self-center">{{ big_goal.title }}</h1>

        <!-- Delete Big Goal Modal -->
        <div id="delete-big-goal-modal" class="modal">
          <div class="modal-center">
            <div class="delete-big-goal-modal-content">
              {% comment %} Header {% endcomment %}
              <div class="text-center mb-5">
                <h3 class="mb-5">
                  Are you sure you want to delete this Big Goal?
                </h3>
                <p class="fw-light fs-3 text-center text-body-secondary">{{big_goal.title}}</p>
              </div>
    
              <div class="d-flex justify-content-end gap-4">
                <button type="button" id="close-delete-big-goal-modal"
                  class="w-50 border py-3 fs-4 bg-transparent box-radius">
                  Close
                </button>
                <button type="button" id="delete-now-btn" class="w-50 border py-3 fs-4 delete-now-btn box-radius">
                  Delete Now
                </button>
              </div>
            </div>
          </div>
        </div>
    
        <button class="delete-big-goal-btn fs-5" id="open-delete-big-goal-modal">
          <i class="bi bi-trash3"></i> 
          <span class="toggle-text">Delete Big Goal</span>
        </button>
      </div>

      {% if big_goal.description %}
        <p class="fs-3 mt-4">{{big_goal.description}}</p>
      {% endif %}
    </section>

    <section class="timeline-section box-radius">
      <input type="hidden" id="no-edit-title-hidden" value="{{title_unedited}}" />
      <input type="hidden" id="title-hidden" value="{{big_goal.title}}" />
      <input type="hidden" id="description-hidden" value="{{big_goal.description}}" />
      <input type="hidden" id="start-hidden" value="{{timeline.start}}" />
      <input type="hidden" id="deadline-hidden" value="{{timeline.deadline}}" />
      <input type="hidden" id="bg-daily-systems" value="{{actions}}" />

      <div id="month-year"></div>

      {% comment %} Timeline {% endcomment %}
      <div class="timeline" id="timeline">
        {% for date in timeline.all_dates %}
        <div class="timeline-item" data-date={{date.current}}>
          <div class="timeline-item--head">
            <span class="m-0">{{ date.current|slice:":3" }}</span>
            <span class="timeline-item--head-day">{{ date.current|slice:"8:10" }}</span>
          </div>
          <div class="timeline-item--body">
            {% for system in daily_systems %}
            <div class="daily-system-box box-radius" data-big-goal={{system.big_goal}}>
              {% if system.action in date.actions %}
              <span class="daily-system-box--checkbox daily-system-box--check"><i class="bi bi-check-circle"></i></span>
              <h5 class="m-0 fw-normal daily-system-box--text daily-system-box--check">{{ system.action }}</h5>
              {% else %}
              <span class="daily-system-box--checkbox"><i class="bi bi-circle"></i></span>
              <h5 class="m-0 fw-normal daily-system-box--text">{{ system.action }}</h5>
              {% endif %}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endfor %}
      </div>
    </section>

    <section class="goal-details-section">
      <div class="big-goal-content--headers">
        <h2 class="fw-normal m-0 align-self-center">
          {% if daily_systems %}
            Daily Actions
          {% else %}
            Start adding your daily actions!
          {% endif %}
        </h1>

        <!-- Create Daily System Modal -->
        <div id="daily-system-modal" class="modal">
          <div class="modal-center">
            <div class="daily-system-modal-content" id="daily-system-modal-content">
              {% comment %} Header {% endcomment %}
              <h3 class="fw-light mb-5">
                What would you do <span class="fst-italic fw-normal"> daily</span> to make it a reality?
              </h3>

              <span id="daily-system-message" class="text-danger fs-5 fw-light"></span>

              {% comment %} Body {% endcomment %}
              <form id="daily-system-form">
                {% csrf_token %}
                <div class="mb-5">
                  <input autofocus class="form-control p-4 fs-4 bg-body-tertiary box-radius" type="text"
                    id="daily-system-title" name="daily-system-title" required />
                </div>

                <div class="d-flex justify-content-end gap-4">
                  <button type="button" id="close-daily-system-modal" class="p-4 border-0 bg-transparent fs-4 box-radius">
                    Close
                  </button>
                  <button type="submit" class="p-4 border-0 fs-4 box-radius submit-modal-bg">
                    Create Daily Action
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>

        <button class="add-daily-goal-btn fs-5" id="open-daily-system-modal">
          <i class="bi bi-plus-lg"></i>
          <span class="toggle-text">Add Daily Action</span>
        </button>
      </div>

      {% if daily_systems %}
        <div class="big-goal-content--daily-systems">
          {% for system in daily_systems %}
            <div class="big-goal-content--daily-system" data-daily-system-id={{system.id}}>
              <span class="daily-system-box--text">{{system.action}}</span>
              <span class="daily-system-box--delete-icon fs-5"><i class="bi bi-trash3"></i></span>
            </div>
          {% endfor %}
        </div>
      {% endif %}
    </section>
  </div>
</main>

{% endblock %}

base/goals_tracker/templates/goals_tracker/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />

  <link href="{% static 'goals_tracker/styles.css' %}" rel="stylesheet" />

  <script src="https://kit.fontawesome.com/363a78aff8.js" crossorigin="anonymous"></script>

  <title>{% block title %}Goal Tracker{% endblock %}</title>
</head>

<body>

  <div class="app-container">
    {% block header %}
    <header class="d-flex align-items-center justify-content-center px-4">
      <div class="main-sidebar" id="main-sidebar">
        <div class="main-sidebar--profile">
          <div class="main-sidebar--profile-logo">
            <a href="{% url 'goals_tracker:index' %}">
              <img src="{% static 'goals_tracker/images/default.png' %}" alt="Goal Tracker logo">
            </a>
          </div>
          <div class="main-sidebar--profile-name fs-3 fw-light" id="profile-header"></div>
        </div>

        <div class="main-sidebar--nav">
          <a href="{% url 'goals_tracker:index' %}" class="main-sidebar--nav-dashboard fs-3 fw-light">
            <i class="bi bi-house"></i>
            <span>Home</span>
          </a>

          <a href="{% url 'goals_tracker:logout' %}" class="main-sidebar--nav-logout fs-3 fw-light">
            <i class="bi bi-box-arrow-right"></i>
            {% comment %} <span>Log out</span> {% endcomment %}
          </a>
        </div>
      </div> 

      <div class="mobile-sidebar" id="mobile-sidebar">
        {% comment %} <a href="{% url 'goals_tracker:index' %}" class="text-decoration-none text-black">
          <img class="logo box-radius" src="{% static 'goals_tracker/images/cover.png' %}" alt="Goal Tracker logo">
        </a> {% endcomment %}

        <div class="mobile-sidebar--nav" id="mobile-sidebar-nav">
          <a href="{% url 'goals_tracker:index' %}" class="mobile-sidebar--nav-item fs-2 fw-light box-radius"
            id="mobile-sidebar-dashboard">
            <i class="bi bi-house"></i>
            <span class="fs-4">Home</span>
          </a>

          <a href="{% url 'goals_tracker:logout' %}" class="mobile-sidebar--nav-item logout fs-2 fw-light box-radius">
            <i class="bi bi-box-arrow-right"></i>
            <span class="fs-4">Log out</span>
          </a>
        </div>
      </div>
    </header>
    {% endblock %}
    
    {% block body %} {% endblock %}
  </div>

  <script src="{% static 'goals_tracker/utils.js' %}"></script>
  <script src="{% static 'goals_tracker/home.js' %}"></script>
  <script src="{% static 'goals_tracker/big_goal.js' %}"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>

    <!-- Firebase SDK -->
  <script src="https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/10.7.1/firebase-messaging.js"></script>

  <script>
    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    const firebaseConfig = {
      apiKey: "AIzaSyBaMZLh3M63kz--zNpLbv_Iwx_GTEQrigI",
      authDomain: "goaltracker-a90fb.firebaseapp.com",
      projectId: "goaltracker-a90fb",
      storageBucket: "goaltracker-a90fb.firebasestorage.app",
      messagingSenderId: "453727782397",
      appId: "1:453727782397:web:2d5f1124b597fecf9d8594",
      measurementId: "G-CCR60T88JQ"
    };
        
    // Initialize Firebase
    const app = initializeApp(firebaseConfig);

    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/static/firebase-messaging-sw.js')
        .then((registration) => {
          console.log('Service Worker registered:', registration);
        })
        .catch((error) => {
          console.error('Service Worker registration failed:', error);
        });
    }
  
    const messaging = firebase.messaging();
  
    // Request permission for notifications
    function requestNotificationPermission() {
      messaging.requestPermission()
        .then(() => {
          console.log('Notification permission granted.');
          return messaging.getToken();
        })
        .then((token) => {
          console.log('FCM Token:', token);
          sendTokenToServer(token);
        })
        .catch((error) => {
          console.error('Unable to get permission:', error);
        });
    }
  
    // Send the token to your Django backend
    function sendTokenToServer(token) {
      fetch('/save_fcm_token/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRFToken': '{{ csrf_token }}',
        },
        body: JSON.stringify({ token: token }),
      });
    }
  
    requestNotificationPermission();
  </script>
</body>
</html>

base/goals_tracker/templates/goals_tracker/login.html
{% extends "goals_tracker/layout.html" %} 
{% block title %} 
Login - Goal Tracker
{% endblock %} 

{% block header %} 
{% endblock%} 

{% block body %}
<div class="row container-fluid m-0 p-0 login-page">
  <div class="error-banner">
    {% for key, value in errors.items %} {% if value %}
    <div
      class="alert alert-danger alert-dismissible fade show error-alert"
      role="alert"
    >
      <span class="fs-5">{{ value }}</span>
      <button
        type="button"
        class="border-0 bg-transparent fs-4"
        data-bs-dismiss="alert"
        aria-label="Close"
      >
        <i class="bi bi-x"></i>
      </button>
    </div>
    {% endif %} {% endfor %}
  </div>

  <div class="col-sm-7 col-md-6 col-lg-5 col-xl-4 vh-100 d-flex flex-column justify-content-center mx-auto">
    <div class="login-container">
      <div class="mb-5">
        <h1 class="display-6 mb-5">Goals Tracker</h1>

        <h2 class="fs-1 fw-normal mb-3">Login to your account.</h2>

        <p class="fs-5 text-secondary">
          Enter your username and password to login.
        </p>
      </div>

      <div class="mb-4">
        <form action="{% url 'goals_tracker:login' %}" method="post">
          {% csrf_token %}
          <div class="form-group mb-4">
            <input
              autofocus
              class="form-control p-3 fs-4"
              type="text"
              name="username"
              placeholder="Usename"
              required
            />
          </div>
          <div class="form-group mb-4">
            <input
              class="form-control p-3 fs-4"
              type="password"
              name="password"
              placeholder="Password"
              required
            />
          </div>
          <input
            class="btn btn-color w-100 p-3 fs-4"
            type="submit"
            value="Login"
          />
        </form>
      </div>

      <div class="fs-5">
        Don't have an account?
        <a href="{% url 'goals_tracker:register' %}" class="text-decoration-none span-green"
          >Register</a
        >
      </div>
    </div>  
  </div>
</div>
{% endblock %}

base/goals_tracker/templates/goals_tracker/register.html
{% extends "goals_tracker/layout.html" %} 

{% block title %} 
Register - Goal Tracker {% endblock %} 

{% block header %} 
{% endblock%} 

{% block body %}
<div class="row container-fluid m-0 p-0 login-page">
  <div class="error-banner">
    {% for key, value in errors.items %} {% if value %}
    <div
      class="alert alert-danger alert-dismissible fade show error-alert"
      role="alert"
    >
      <span class="fs-5">{{ value }}</span>
      <button
        type="button"
        class="border-0 bg-transparent fs-4"
        data-bs-dismiss="alert"
        aria-label="Close"
      >
        <i class="bi bi-x"></i>
      </button>
    </div>
    {% endif %} {% endfor %}
  </div>

  <div class="col-sm-7 col-md-6 col-lg-5 col-xl-4 vh-100 d-flex flex-column justify-content-center mx-auto">
    <div class="login-container">
      <div class="mb-5">
        <h1 class="display-6 mb-5">Goals Tracker</h1>
        <h2 class="fs-1 fw-normal mb-3">Register an account.</h2>
      </div>

      <div class="mb-4">
        <form action="{% url 'goals_tracker:register' %}" method="post">
          {% csrf_token %}
          <!-- Username -->
          <div class="form-group mb-4">
            <input
              autofocus
              class="form-control p-3 fs-4"
              type="text"
              name="username"
              placeholder="Username"
              required
            />
          </div>

          <!-- Email -->
          <div class="form-group mb-4">
            <input
              autofocus
              class="form-control p-3 fs-4"
              type="email"
              name="email"
              placeholder="Email"
              required
            />
          </div>

          <!-- Password -->
          <div class="form-group mb-4">
            <input
              class="form-control p-3 fs-4"
              type="password"
              name="password"
              placeholder="Password"
              required
            />
          </div>

          <!-- Confirm Password -->
          <div class="form-group mb-4">
            <input
              class="form-control p-3 fs-4"
              type="password"
              name="confirmation"
              placeholder="Confirm Password"
              required
            />
          </div>

          <input
            class="btn btn-color w-100 p-3 fs-4"
            type="submit"
            value="Register"
          />
        </form>
      </div>

      <div class="fs-5">
        Already have an account?
        <a href="{% url 'goals_tracker:login' %}" class="text-decoration-none span-green"
          >Login</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock %}